# Increase Volume
bindel = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
# Decrease Volume
bindel = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
# Mute/Unmute Audio
bindl = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

# Increase Brightness
bindel = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
# Decrease Brightness
bindel = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower
