source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/monitors/arrangement.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/monitors/workspaces.conf
source = ~/.config/hypr/screenshots.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/waybar-floats.conf
source = ~/.config/hypr/touchpad.conf
# HyprMod managed settings
source = ~/.config/hypr/hyprland-gui.conf

# Layout
general {
    layout = dwindle
}

dwindle {
    preserve_split = true
}

# System config
input {
   follow_mouse = 2
   kb_layout = us
   kb_options = caps:escape
   touchpad {
      natural_scroll = true
   }
}
cursor {
   no_warps = false
}

# env vars
env = GTK_USE_PORTAL,1
env = GDK_DEBUG,portals

