-- Generated by nwg-displays on 2026-09-16 at 13:57:21. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "3440x610",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@50.0",
    position = "0x250",
    scale = 1,
    vrr = 0
})
