-- Generated by nwg-displays on 2026-10-06 at 09:01:57. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "9712x451",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1200@59.95",
    position = "7792x0",
    scale = 1,
    vrr = 0
})
