# Waybar Floating Window Rules
windowrule = float true, match:class btop-float
windowrule = size 900 600, match:class btop-float
windowrule = center true, match:class btop-float

windowrule = float true, match:class pulsemixer-float
windowrule = size 700 400, match:class pulsemixer-float
windowrule = center true, match:class pulsemixer-float

windowrule = float true, match:class tsui-float
windowrule = size 700 400, match:class tsui-float
windowrule = center true, match:class tsui-float

windowrule = float true, match:class impala-float
windowrule = size 700 400, match:class impala-float
windowrule = center true, match:class impala-float

windowrule = float true, match:class weather-float
windowrule = center true, match:class weather-float

windowrule = float true, match:class bluetui-float
windowrule = size 700 400, match:class bluetui-float
windowrule = center true, match:class bluetui-float
