# Window Rules
windowrule = float true, match:class yazi-float
windowrule = size 80% 80%, match:class yazi-float
windowrule = center true, match:class yazi-float

windowrule = float true, match:class Bitwarden
windowrule = center true, match:class Bitwarden

windowrule = float true, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default
windowrule = center true, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default
windowrule = size 600 800, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default

windowrule = float true, match:class file_chooser
windowrule = size 900 600, match:class file_chooser
windowrule = center true, match:class file_chooser

# Yazi File Chooser Popup Rules
windowrule = float on, match:class ^(file_chooser)$
windowrule = center on, match:class ^(file_chooser)$
windowrule = size 1000 650, match:class ^(file_chooser)$

# Startup workspace assignments (Helium PWAs ignore exec workspace rules when browser is already running)
windowrule = workspace 5 silent, match:class crx_hnpfjngllnobngcgfapefoaidbinmjnm
windowrule = workspace 7 silent, match:class crx_kjbdgfilnfhdoflbpgamdcdgpehopbep

# Rofi blur
layerrule = blur on, ignore_alpha 1,match:namespace rofi
