# Window Rules
windowrule = float true, match:class btop-float
windowrule = size 900 600, match:class btop-float
windowrule = center true, match:class btop-float

windowrule = float true, match:class pulsemixer-float
windowrule = size 700 400, match:class pulsemixer-float
windowrule = center true, match:class pulsemixer-float

windowrule = float true, match:class impala-float
windowrule = size 700 400, match:class impala-float
windowrule = center true, match:class impala-float

windowrule = float true, match:class weather-float
windowrule = center true, match:class weather-float

windowrule = float true, match:class bluetui-float
windowrule = size 700 400, match:class bluetui-float
windowrule = center true, match:class bluetui-float

windowrule = float true, match:class yazi-float
windowrule = size 80% 80%, match:class yazi-float
windowrule = center true, match:class yazi-float

windowrule = float true, match:class Bitwarden
windowrule = center true, match:class Bitwarden

windowrule = float true, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default
windowrule = center true, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default
windowrule = size 400 600, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default

windowrule = float true, match:class file_chooser
windowrule = size 900 600, match:class file_chooser
windowrule = center true, match:class file_chooser

# Yazi File Chooser Popup Rules
windowrule = float on, match:class ^(file_chooser)$
windowrule = center on, match:class ^(file_chooser)$
windowrule = size 1000 650, match:class ^(file_chooser)$

# Rofi blur
layerrule = blur on, ignore_alpha 1,match:namespace rofi
